# 2021-11-19 - hieuhihi

LAYER_1 = '1.NET THAY THUNG TU'
LAYER_2 = '2.NET TUONG'
LAYER_3 = '3.NET KHUAT'
LAYER_4 = '4.NET CANH _ MAT HOC KEO'
LAYER_5 = '5.NET DIM'
LAYER_6 = '6.NET KHUNG TEN'
LAYER_7 = '7.NET CHU'
LAYER_8 = '8.NET PHU KIEN'
LAYER_9 = '9.MAT DA'


